--
-- PostgreSQL database dump
--

\restrict eQsMO7paYfqFOmVE2sCHUxwQtONi3xhOoJsRmE4V2Yu1dsTLvX1G5ZLQPqlfXfO

-- Dumped from database version 16.15 (Homebrew)
-- Dumped by pg_dump version 16.15 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clinica_atencion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clinica_atencion (
    id bigint NOT NULL,
    fecha date NOT NULL,
    motivo character varying(150) NOT NULL,
    diagnostico text NOT NULL,
    costo_neto numeric(9,0) NOT NULL,
    estado character varying(3) NOT NULL,
    mascota_id bigint NOT NULL,
    veterinario_id bigint NOT NULL
);


--
-- Name: clinica_atencion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clinica_atencion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clinica_atencion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clinica_dueno; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clinica_dueno (
    id bigint NOT NULL,
    rut character varying(12) NOT NULL,
    nombre character varying(60) NOT NULL,
    apellido character varying(60) NOT NULL,
    email character varying(254) NOT NULL,
    telefono character varying(15) NOT NULL,
    direccion character varying(150) NOT NULL,
    fecha_registro date NOT NULL
);


--
-- Name: clinica_dueno_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clinica_dueno ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clinica_dueno_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clinica_especie; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clinica_especie (
    id bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    nombre_cientifico character varying(100) NOT NULL,
    cuidados_generales text NOT NULL
);


--
-- Name: clinica_especie_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clinica_especie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clinica_especie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clinica_mascota; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clinica_mascota (
    id bigint NOT NULL,
    nombre character varying(60) NOT NULL,
    sexo character varying(1) NOT NULL,
    fecha_nacimiento date NOT NULL,
    peso_kg numeric(5,2) NOT NULL,
    activa boolean NOT NULL,
    dueno_id bigint NOT NULL,
    especie_id bigint NOT NULL
);


--
-- Name: clinica_mascota_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clinica_mascota ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clinica_mascota_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clinica_veterinario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clinica_veterinario (
    id bigint NOT NULL,
    nombre character varying(60) NOT NULL,
    apellido character varying(60) NOT NULL,
    email character varying(254) NOT NULL,
    especialidad character varying(80) NOT NULL,
    activo boolean NOT NULL
);


--
-- Name: clinica_veterinario_especies_atendidas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clinica_veterinario_especies_atendidas (
    id bigint NOT NULL,
    veterinario_id bigint NOT NULL,
    especie_id bigint NOT NULL
);


--
-- Name: clinica_veterinario_especies_atendidas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clinica_veterinario_especies_atendidas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clinica_veterinario_especies_atendidas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clinica_veterinario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clinica_veterinario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clinica_veterinario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add dueño	7	add_dueno
26	Can change dueño	7	change_dueno
27	Can delete dueño	7	delete_dueno
28	Can view dueño	7	view_dueno
29	Can add especie	8	add_especie
30	Can change especie	8	change_especie
31	Can delete especie	8	delete_especie
32	Can view especie	8	view_especie
33	Can add mascota	9	add_mascota
34	Can change mascota	9	change_mascota
35	Can delete mascota	9	delete_mascota
36	Can view mascota	9	view_mascota
37	Can add veterinario	10	add_veterinario
38	Can change veterinario	10	change_veterinario
39	Can delete veterinario	10	delete_veterinario
40	Can view veterinario	10	view_veterinario
41	Can add atención	11	add_atencion
42	Can change atención	11	change_atencion
43	Can delete atención	11	delete_atencion
44	Can view atención	11	view_atencion
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
2	pbkdf2_sha256$1000000$3wai8cTPIaSpS1zxm22CLe$ZaxJn4yUl1KCzSeqk2/tqep30jEoCE0rULutODet0ek=	\N	f	recepcion			recepcion@patitas.cl	f	t	2026-09-14 09:07:42.522029-03
1	pbkdf2_sha256$1000000$PGbLj07vtrPbw2rSVe4HcB$F6maMSBdKqTiaZ+nD+G29BHFxkkqq5H8n0ScH8QrFcE=	2026-09-14 09:09:11.222962-03	t	admin			admin@patitas.cl	t	t	2026-09-14 09:07:42.449333-03
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: clinica_atencion; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.clinica_atencion (id, fecha, motivo, diagnostico, costo_neto, estado, mascota_id, veterinario_id) FROM stdin;
1	2026-03-04	Control anual y vacuna séxtuple	Paciente en buen estado general. Se aplica refuerzo de vacuna.	28000	REA	1	1
2	2026-04-17	Vómitos intermitentes	Gastritis leve. Se indica dieta blanda por 5 días.	32000	REA	2	1
3	2026-05-08	Cojera en pata trasera derecha	Sospecha de luxación rotuliana grado II. Se solicita radiografía.	45000	REA	3	2
4	2026-06-21	Control dental	Sobrecrecimiento de incisivos. Se realiza limado.	38000	REA	4	3
5	2026-07-03	Desparasitación interna	Sin hallazgos. Se administra antiparasitario oral.	18000	REA	5	1
6	2026-07-29	Herida en almohadilla plantar	Corte superficial. Se limpia y venda.	25000	REA	6	2
7	2026-08-12	Pérdida de plumaje	Muda estacional dentro de lo normal. Se ajusta dieta.	22000	REA	7	3
8	2026-09-02	Esterilización programada		120000	PEN	8	2
9	2026-09-10	Primera consulta y vacuna triple felina		30000	PEN	9	1
10	2026-09-12	Control de peso		15000	PEN	10	3
\.


--
-- Data for Name: clinica_dueno; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.clinica_dueno (id, rut, nombre, apellido, email, telefono, direccion, fecha_registro) FROM stdin;
1	12345678-5	María	González	maria.gonzalez@correo.cl	+56912345678	Av. Los Leones 1245, Providencia	2026-09-14
2	9876543-3	Pedro	Ramírez	pramirez@correo.cl	+56987654321	Calle Serrano 480, Valparaíso	2026-09-14
3	15678234-3	Camila	Soto	camila.soto@correo.cl	+56955512340	Pasaje Los Robles 78, Maipú	2026-09-14
4	17456789-5	Jorge	Muñoz	jmunoz@correo.cl	+56944498211	Av. Alemania 3390, Temuco	2026-09-14
5	11222333-8	Valentina	Rojas	vrojas@correo.cl	+56966677889	El Vergel 220, Ñuñoa	2026-09-14
\.


--
-- Data for Name: clinica_especie; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.clinica_especie (id, nombre, nombre_cientifico, cuidados_generales) FROM stdin;
1	Canino	Canis lupus familiaris	Vacuna séxtuple anual y desparasitación cada 3 meses.
2	Felino	Felis catus	Vacuna triple felina anual. Control de pulgas mensual.
3	Conejo	Oryctolagus cuniculus	Dieta alta en fibra. Control dental semestral.
4	Ave	Serinus canaria	Evitar corrientes de aire. Control de plumaje.
\.


--
-- Data for Name: clinica_mascota; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.clinica_mascota (id, nombre, sexo, fecha_nacimiento, peso_kg, activa, dueno_id, especie_id) FROM stdin;
1	Rocky	M	2019-03-14	28.50	t	1	1
2	Luna	H	2021-07-02	4.20	t	1	2
3	Simón	M	2016-11-25	12.80	t	2	1
4	Pelusa	H	2023-01-09	1.90	t	2	3
5	Trufa	H	2020-05-30	3.85	t	3	2
6	Bruno	M	2022-09-18	19.40	t	3	1
7	Kiwi	M	2024-02-11	0.35	t	4	4
8	Nala	H	2018-06-06	24.10	t	4	1
9	Michi	M	2023-12-01	3.10	t	5	2
10	Copito	M	2022-04-22	2.35	t	5	3
\.


--
-- Data for Name: clinica_veterinario; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.clinica_veterinario (id, nombre, apellido, email, especialidad, activo) FROM stdin;
1	Andrés	Fuentes	afuentes@patitas.cl	Medicina interna de pequeños animales	t
2	Paula	Bravo	pbravo@patitas.cl	Cirugía y traumatología	t
3	Ignacio	Cárdenas	icardenas@patitas.cl	Animales exóticos	t
\.


--
-- Data for Name: clinica_veterinario_especies_atendidas; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.clinica_veterinario_especies_atendidas (id, veterinario_id, especie_id) FROM stdin;
1	1	1
2	1	2
3	2	1
4	2	2
5	2	3
6	3	3
7	3	4
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	clinica	dueno
8	clinica	especie
9	clinica	mascota
10	clinica	veterinario
11	clinica	atencion
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-09-14 09:07:38.451313-03
2	auth	0001_initial	2026-09-14 09:07:38.476692-03
3	admin	0001_initial	2026-09-14 09:07:38.483047-03
4	admin	0002_logentry_remove_auto_add	2026-09-14 09:07:38.484666-03
5	admin	0003_logentry_add_action_flag_choices	2026-09-14 09:07:38.486277-03
6	contenttypes	0002_remove_content_type_name	2026-09-14 09:07:38.489813-03
7	auth	0002_alter_permission_name_max_length	2026-09-14 09:07:38.491691-03
8	auth	0003_alter_user_email_max_length	2026-09-14 09:07:38.494012-03
9	auth	0004_alter_user_username_opts	2026-09-14 09:07:38.495511-03
10	auth	0005_alter_user_last_login_null	2026-09-14 09:07:38.497345-03
11	auth	0006_require_contenttypes_0002	2026-09-14 09:07:38.497915-03
12	auth	0007_alter_validators_add_error_messages	2026-09-14 09:07:38.499342-03
13	auth	0008_alter_user_username_max_length	2026-09-14 09:07:38.502915-03
14	auth	0009_alter_user_last_name_max_length	2026-09-14 09:07:38.504593-03
15	auth	0010_alter_group_name_max_length	2026-09-14 09:07:38.506875-03
16	auth	0011_update_proxy_permissions	2026-09-14 09:07:38.508298-03
17	auth	0012_alter_user_first_name_max_length	2026-09-14 09:07:38.509882-03
18	clinica	0001_initial	2026-09-14 09:07:38.53519-03
19	sessions	0001_initial	2026-09-14 09:07:38.538893-03
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
ot1wa7pk9a4h9uozjclw22ij673boutg	.eJxVjEEOwiAQRe_C2hBKsUxduvcMZGYYpGogKe3KeHdD0oVu_3vvv1XAfcthb7KGJaqLGtTpdyPkp5QO4gPLvWquZVsX0l3RB236VqO8rof7d5Cx5V6z9wg0kUVronif2M-jM47AzzwMMBoGmUTOCS0zCxlggkROLBCh-nwB_P85Ig:1x65Ul:ruI4bPj9fVbW7ptbbpL6ziURGmctB3ZUzur06C_XjW4	2026-09-28 09:09:11.223746-03
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 44, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: clinica_atencion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.clinica_atencion_id_seq', 10, true);


--
-- Name: clinica_dueno_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.clinica_dueno_id_seq', 5, true);


--
-- Name: clinica_especie_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.clinica_especie_id_seq', 4, true);


--
-- Name: clinica_mascota_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.clinica_mascota_id_seq', 11, true);


--
-- Name: clinica_veterinario_especies_atendidas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.clinica_veterinario_especies_atendidas_id_seq', 7, true);


--
-- Name: clinica_veterinario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.clinica_veterinario_id_seq', 3, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 11, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 19, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: clinica_atencion clinica_atencion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clinica_atencion
    ADD CONSTRAINT clinica_atencion_pkey PRIMARY KEY (id);


--
-- Name: clinica_dueno clinica_dueno_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clinica_dueno
    ADD CONSTRAINT clinica_dueno_pkey PRIMARY KEY (id);


--
-- Name: clinica_dueno clinica_dueno_rut_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clinica_dueno
    ADD CONSTRAINT clinica_dueno_rut_key UNIQUE (rut);


--
-- Name: clinica_especie clinica_especie_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clinica_especie
    ADD CONSTRAINT clinica_especie_nombre_key UNIQUE (nombre);


--
-- Name: clinica_especie clinica_especie_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clinica_especie
    ADD CONSTRAINT clinica_especie_pkey PRIMARY KEY (id);


--
-- Name: clinica_mascota clinica_mascota_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clinica_mascota
    ADD CONSTRAINT clinica_mascota_pkey PRIMARY KEY (id);


--
-- Name: clinica_veterinario clinica_veterinario_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clinica_veterinario
    ADD CONSTRAINT clinica_veterinario_email_key UNIQUE (email);


--
-- Name: clinica_veterinario_especies_atendidas clinica_veterinario_espe_veterinario_id_especie_i_7b6c2153_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clinica_veterinario_especies_atendidas
    ADD CONSTRAINT clinica_veterinario_espe_veterinario_id_especie_i_7b6c2153_uniq UNIQUE (veterinario_id, especie_id);


--
-- Name: clinica_veterinario_especies_atendidas clinica_veterinario_especies_atendidas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clinica_veterinario_especies_atendidas
    ADD CONSTRAINT clinica_veterinario_especies_atendidas_pkey PRIMARY KEY (id);


--
-- Name: clinica_veterinario clinica_veterinario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clinica_veterinario
    ADD CONSTRAINT clinica_veterinario_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: clinica_atencion_mascota_id_bd6ba3b0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX clinica_atencion_mascota_id_bd6ba3b0 ON public.clinica_atencion USING btree (mascota_id);


--
-- Name: clinica_atencion_veterinario_id_1d3e28aa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX clinica_atencion_veterinario_id_1d3e28aa ON public.clinica_atencion USING btree (veterinario_id);


--
-- Name: clinica_dueno_rut_35ecfa32_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX clinica_dueno_rut_35ecfa32_like ON public.clinica_dueno USING btree (rut varchar_pattern_ops);


--
-- Name: clinica_especie_nombre_dae8a079_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX clinica_especie_nombre_dae8a079_like ON public.clinica_especie USING btree (nombre varchar_pattern_ops);


--
-- Name: clinica_mascota_dueno_id_ebc94278; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX clinica_mascota_dueno_id_ebc94278 ON public.clinica_mascota USING btree (dueno_id);


--
-- Name: clinica_mascota_especie_id_37d4f614; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX clinica_mascota_especie_id_37d4f614 ON public.clinica_mascota USING btree (especie_id);


--
-- Name: clinica_veterinario_email_c1c6bd26_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX clinica_veterinario_email_c1c6bd26_like ON public.clinica_veterinario USING btree (email varchar_pattern_ops);


--
-- Name: clinica_veterinario_especies_atendidas_especie_id_8ecca4f6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX clinica_veterinario_especies_atendidas_especie_id_8ecca4f6 ON public.clinica_veterinario_especies_atendidas USING btree (especie_id);


--
-- Name: clinica_veterinario_especies_atendidas_veterinario_id_f5eeebeb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX clinica_veterinario_especies_atendidas_veterinario_id_f5eeebeb ON public.clinica_veterinario_especies_atendidas USING btree (veterinario_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clinica_atencion clinica_atencion_mascota_id_bd6ba3b0_fk_clinica_mascota_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clinica_atencion
    ADD CONSTRAINT clinica_atencion_mascota_id_bd6ba3b0_fk_clinica_mascota_id FOREIGN KEY (mascota_id) REFERENCES public.clinica_mascota(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clinica_atencion clinica_atencion_veterinario_id_1d3e28aa_fk_clinica_v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clinica_atencion
    ADD CONSTRAINT clinica_atencion_veterinario_id_1d3e28aa_fk_clinica_v FOREIGN KEY (veterinario_id) REFERENCES public.clinica_veterinario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clinica_mascota clinica_mascota_dueno_id_ebc94278_fk_clinica_dueno_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clinica_mascota
    ADD CONSTRAINT clinica_mascota_dueno_id_ebc94278_fk_clinica_dueno_id FOREIGN KEY (dueno_id) REFERENCES public.clinica_dueno(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clinica_mascota clinica_mascota_especie_id_37d4f614_fk_clinica_especie_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clinica_mascota
    ADD CONSTRAINT clinica_mascota_especie_id_37d4f614_fk_clinica_especie_id FOREIGN KEY (especie_id) REFERENCES public.clinica_especie(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clinica_veterinario_especies_atendidas clinica_veterinario__especie_id_8ecca4f6_fk_clinica_e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clinica_veterinario_especies_atendidas
    ADD CONSTRAINT clinica_veterinario__especie_id_8ecca4f6_fk_clinica_e FOREIGN KEY (especie_id) REFERENCES public.clinica_especie(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clinica_veterinario_especies_atendidas clinica_veterinario__veterinario_id_f5eeebeb_fk_clinica_v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clinica_veterinario_especies_atendidas
    ADD CONSTRAINT clinica_veterinario__veterinario_id_f5eeebeb_fk_clinica_v FOREIGN KEY (veterinario_id) REFERENCES public.clinica_veterinario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict eQsMO7paYfqFOmVE2sCHUxwQtONi3xhOoJsRmE4V2Yu1dsTLvX1G5ZLQPqlfXfO

