# Generated by Django 5.2.17 on 2026-09-14 12:07

import clinica.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='Formato 12345678-9', max_length=12, unique=True, validators=[clinica.models.validar_rut])),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(blank=True, max_length=150)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'dueño',
                'verbose_name_plural': 'dueños',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=100)),
                ('cuidados_generales', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'especie',
                'verbose_name_plural': 'especies',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('200'))], verbose_name='peso (kg)')),
                ('activa', models.BooleanField(default=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='clinica.dueno', verbose_name='dueño')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mascotas', to='clinica.especie')),
            ],
            options={
                'verbose_name': 'mascota',
                'verbose_name_plural': 'mascotas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('especialidad', models.CharField(max_length=80)),
                ('activo', models.BooleanField(default=True)),
                ('especies_atendidas', models.ManyToManyField(blank=True, related_name='veterinarios', to='clinica.especie')),
            ],
            options={
                'verbose_name': 'veterinario',
                'verbose_name_plural': 'veterinarios',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=150)),
                ('diagnostico', models.TextField(blank=True)),
                ('costo_neto', models.DecimalField(decimal_places=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='costo neto ($)')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('REA', 'Realizada'), ('ANU', 'Anulada')], default='PEN', max_length=3)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='clinica.mascota')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='clinica.veterinario')),
            ],
            options={
                'verbose_name': 'atención',
                'verbose_name_plural': 'atenciones',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
